export const GET_SIZE = "GETSIZE"
export const SEARCH_SIZE = "SEARCH_SIZE"
export const GET_PRODUCT = "GET_PRODUCT"
export const ADD_CART = "ADD_CART"
export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART"
export const SORT_PRICE = "SORT_PRICE"